global:
  scrape_interval:     1s
  external_labels:
    userRange: '1'

scrape_configs:
  - job_name: 'mockstagram'
    file_sd_configs:
      - files:
        - /etc/prometheus/targets.json
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '(go_.*)'
        action: drop