kind: Service
apiVersion: v1
metadata:
  name: mockstagram-serivce
  labels:
        run: mockstagram
spec:
    selector:
        app: mockstagram
    clusterIP: 10.96.30.30
    ports:
    -   protocol: TCP
        port: 3000
        targetPort: 3000 
        nodePort: 31300
    type: NodePort